"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
# ==============================================================================
# SOLUÇÃO DEFINITIVA: CORREÇÃO DE DATAS (MIGRAÇÃO SQLITE -> MYSQL)
# ==============================================================================
import datetime
import pymysql
from dateutil import parser
from django.db.backends.mysql import operations
from django.utils import timezone
from typing import Any

# 1. Inicializa o PyMySQL como o driver oficial do Django
pymysql.install_as_MySQLdb()

# 2. Corretor para DateTimeField (Campos com Data e Hora)
def convert_datetime_safe(self: Any, value: Any, expression: Any, connection: Any) -> Any:
    if isinstance(value, str):
        try:
            value = parser.parse(value)
        except Exception:
            pass
            
    if isinstance(value, datetime.datetime):
        if value.tzinfo is None:
            value = timezone.make_aware(value, connection.timezone)
        
    return value

# Aplica o corretor nativo de DateTimeField do Django
operations.DatabaseOperations.convert_datetimefield_value = convert_datetime_safe


# 3. Corretor para DateField (Campos de Data Pura, como a sua validade)
def convert_date_safe_converter(value: Any, expression: Any, connection: Any) -> Any:
    if isinstance(value, str):
        try:
            # Converte o texto do banco e extrai apenas o objeto date do Python
            return parser.parse(value).date()
        except Exception:
            return value
    return value

# 4. Injeção dinâmica no mapeamento de consultas do Django
original_get_db_converters = operations.DatabaseOperations.get_db_converters

def custom_get_db_converters(self: Any, expression: Any) -> list:
    converters = original_get_db_converters(self, expression)
    internal_type = expression.output_field.get_internal_type()
    
    # Se o seu Model do Django diz que o campo é um DateField, nós forçamos
    # a conversão da string, não importa se no MySQL a coluna é DATE ou VARCHAR.
    if internal_type == 'DateField':
        converters.append(convert_date_safe_converter)
        
    return converters

# Aplica o patch global de conversores no Django
operations.DatabaseOperations.get_db_converters = custom_get_db_converters
# ==============================================================================


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Aumenta o limite para 5000 campos (o padrão é 1000)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^z9jk=y%*4$1c)f7y72hx6#&+isj@u)izw)^&f64@17)44wt_o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'banco_migrado',
        'USER': 'root',
        'PASSWORD': 'iT$669722',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

USE_L10N = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    BASE_DIR / 'base_static',
)
STATIC_ROOT = BASE_DIR / 'static'  # collectstatic
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# try:
#     from project.local_settings import *
# except ImportError:
#     ...
